type Climb {
  _id: ID!
  name: String!
  grade: String!
  ascents: [Ascent!]
  crag: Crag
  fa: ID
  description: String
  addedAt: Date!
  updatedAt: Date!
}

input ClimbsFilter {
  name: String
  crag: String
}

input CreateClimbInput {
  name: String!
  grade: String!
  crag: ID
  description: String
}

type Query {
  climb(ID: ID!): Climb
  climbs(filter: ClimbsFilter, limit: Int): [Climb!]
}

type Mutation {
  createClimb(input: CreateClimbInput!): Climb!
  deleteClimb(ID: ID!): Boolean!
}
