type Climber {
  _id: ID!
  name: String!
  nickname: String
  dob: Date
  sex: String
  country: Country
  ascents: [Ascent!]
  description: String
  addedAt: Date!
  updatedAt: Date!
}

input ClimbersFilter {
  name: String
  nickname: String
  country: String
}

input CreateClimberInput {
  name: String!
  nickname: String
  dob: String
  sex: String
  country: ID
  description: String
}

type Query {
  climbers(filter: ClimbersFilter): [Climber!]
  climberByID(ID: ID!): Climber
}

type Mutation {
  createClimber(input: CreateClimberInput!): Climber
  deleteClimber(ID: ID!): Boolean!
}
