type Country {
  _id: ID!
  name: String!
  crags: [Crag!]
  climbers: [Climber!]
  description: String
}

type Query {
  country(ID: ID!): Country
  countryByName(name: String!): Country
  countries: [Country!]
}
