type Country {
  _id: ID!
  name: String!
  ISOcode: String!
  crags: [Crag!]
  climbers: [Climber!]
  description: String
}

input CountriesFilter {
  name: String
}

type Query {
  country(ID: ID!): Country
  countries(filter: CountriesFilter): [Country!]
}
