type Country {
  _id: ID!
  name: String!
  ISOcode: String!
  crags: [Crag!]
  climbers: [Climber!]
  description: String
}

input CountriesFilter {
  name: String
  ISOcode: String
}

input CreateCountryInput {
  name: String!
  ISOcode: String!
}

type Query {
  country(ID: ID!): Country
  countries(filter: CountriesFilter): [Country!]
}

type Mutation {
  createCountry(input: CreateCountryInput!): Country!
}
