type Crag {
  _id: ID!
  name: String!
  country: Country
  climbs: [Climb!]
  description: String
  addedAt: Date!
  updatedAt: Date!
}

input CragInput {
  name: String!
  country: ID
  description: String
}

type Query {
  cragById(ID: ID!): Crag
  cragByName(name: String!): [Crag!]
  crags: [Crag!]
}

type Mutation {
  createCrag(cragInput: CragInput!): Crag!
  deleteCrag(ID: ID!): Boolean!
}
