type Crag {
  _id: ID!
  name: String!
  country: Country
  climbs: [Climb!]
  description: String
  addedAt: Date!
  updatedAt: Date!
}

input CragsFilter {
  name: String
}

input CreateCragInput {
  name: String!
  country: ID
  description: String
}

type Query {
  crag(ID: ID!): Crag
  crags(filter: CragsFilter, limit: Int): [Crag!]
}

type Mutation {
  createCrag(input: CreateCragInput!): Crag!
  deleteCrag(ID: ID!): Boolean!
}
